/**
 * WebApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PostListDto { 
    id?: number;
    answerCount?: number;
    isClosed?: boolean;
    commentCount?: number;
    creationDate?: Date;
    score?: number;
    title?: string;
    shortBody?: string;
    viewCount?: number;
}