name: Stryker Mutation Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  stryker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dotnet-stryker
      run: dotnet tool install dotnet-stryker --tool-path /usr/local/bin
    - name: Run dotnet-stryker
      run: /usr/local/bin/dotnet-stryker --project-file="/home/runner/work/SO/SO/SO/Logic/Logic.csproj"
      working-directory: ./SO/Tests/UnitTests