name: Stryker Mutation Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  stryker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dotnet-stryker
      run: dotnet tool install dotnet-stryker --tool-path /usr/local/bin
    - name: Run dotnet-stryker
      run: /usr/local/bin/dotnet-stryker --project "Logic.csproj"
      working-directory: ./SO/Tests/UnitTests
    - name: Install Python Dependencies
      run: pip install PyGithub
    - name: Update Mutation Score Badge
      working-directory: ./
      run: python ./github/scripts/update_badge.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
